# version: "3.8"

services:
  kube-news:
    image: munizfilho/kbenews:v1
    container_name: kbnews_app
    # depends_on:
    #  - backend
    #restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      TZ: Lisbon/Portugal
      DB_USER: kbnews_user
      DB_PASSWORD: kbnews_password
      DB_DATABASE: kbnews_db
      DB_HOST: backend
    networks:
      - kbnews_netw


  backend:
    image: postgres:12.17
    container_name: kbnews-pgdb
    restart: unless-stopped
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: kbnews_user
      POSTGRES_PASSWORD: kbnews_password
      POSTGRES_DB: kbnews_db
      KBNEWS_DB_SSLMODE: disable
    volumes:
      - kbnews-pg-data:/var/lib/postgresql/data
      # Uncomment below lines if you have SQL scripts to initialize the DB
      # - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./postgres/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - kbnews_netw

volumes:
  kbnews-pg-data:

networks:
  kbnews_netw:
    driver: bridge